# This workflow will automatically deploy your application to www.evennode.com on push to master branch.

name: Deploy to EvenNode

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: " "
    - name: Add git.evennode.com to known_hosts
      run: |
        ssh-keyscan -H git.evennode.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to evennode.com
      run: |
        git remote add evennode ${{ secrets.EVENNODE_REPO_URL }}
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git push evennode +master
